package com.lbr.dao.hibernate.domain;

// Generated Feb 23, 2011 12:34:52 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer cityId;
	private State state;
	private District district;
	private String cityName;
	private Set<Locations> locationses = new HashSet<Locations>(0);

	public City() {
	}

	public City(State state, District district, String cityName) {
		this.state = state;
		this.district = district;
		this.cityName = cityName;
	}

	public City(State state, District district, String cityName,
			Set<Locations> locationses) {
		this.state = state;
		this.district = district;
		this.cityName = cityName;
		this.locationses = locationses;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Set<Locations> getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set<Locations> locationses) {
		this.locationses = locationses;
	}

}
