package com.lbr.dao.hibernate.domain;

// Generated Feb 23, 2011 12:34:52 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private Integer countryId;
	private String countryName;
	private Set<State> states = new HashSet<State>(0);

	public Country() {
	}

	public Country(String countryName) {
		this.countryName = countryName;
	}

	public Country(String countryName, Set<State> states) {
		this.countryName = countryName;
		this.states = states;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}

}
