package com.lbr.dao.hibernate.domain;

// Generated 07-Mar-2011 11:48:20 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private Integer eventId;
	private Subcategory subcategory;
	private Locations locations;
	private Date startDate;
	private Date endDate;
	private String name;
	private Long contactNo;
	private String contactPerson;
	private String address;
	private String details;
	private Date modifiedOn;
	private Integer level;
	private Integer ownerId;
	private String usp;

	public Events() {
	}

	public Events(Subcategory subcategory, Locations locations, Date startDate,
			Date endDate, String name, Long contactNo, String contactPerson,
			String address, String details, Date modifiedOn, Integer level,
			Integer ownerId, String usp) {
		this.subcategory = subcategory;
		this.locations = locations;
		this.startDate = startDate;
		this.endDate = endDate;
		this.name = name;
		this.contactNo = contactNo;
		this.contactPerson = contactPerson;
		this.address = address;
		this.details = details;
		this.modifiedOn = modifiedOn;
		this.level = level;
		this.ownerId = ownerId;
		this.usp = usp;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public Subcategory getSubcategory() {
		return this.subcategory;
	}

	public void setSubcategory(Subcategory subcategory) {
		this.subcategory = subcategory;
	}

	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(Long contactNo) {
		this.contactNo = contactNo;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	public String getUsp() {
		return this.usp;
	}

	public void setUsp(String usp) {
		this.usp = usp;
	}

}
