package com.lbr.dao.hibernate.domain;

// Generated 11-Mar-2011 20:54:26 by Hibernate Tools 3.4.0.Beta1

/**
 * MissinglocationsId generated by hbm2java
 */
public class MissinglocationsId implements java.io.Serializable {

	private int pincode;
	private String locName;
	private String cityName;

	public MissinglocationsId() {
	}

	public MissinglocationsId(int pincode, String locName, String cityName) {
		this.pincode = pincode;
		this.locName = locName;
		this.cityName = cityName;
	}

	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MissinglocationsId))
			return false;
		MissinglocationsId castOther = (MissinglocationsId) other;

		return (this.getPincode() == castOther.getPincode())
				&& ((this.getLocName() == castOther.getLocName()) || (this
						.getLocName() != null && castOther.getLocName() != null && this
						.getLocName().equals(castOther.getLocName())))
				&& ((this.getCityName() == castOther.getCityName()) || (this
						.getCityName() != null
						&& castOther.getCityName() != null && this
						.getCityName().equals(castOther.getCityName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPincode();
		result = 37 * result
				+ (getLocName() == null ? 0 : this.getLocName().hashCode());
		result = 37 * result
				+ (getCityName() == null ? 0 : this.getCityName().hashCode());
		return result;
	}

}
