package com.lbr.dao.hibernate.domain;

// Generated Feb 23, 2011 12:34:52 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private Integer stateId;
	private Country country;
	private String stateName;
	private Set<District> districts = new HashSet<District>(0);
	private Set<City> cities = new HashSet<City>(0);

	public State() {
	}

	public State(Country country, String stateName) {
		this.country = country;
		this.stateName = stateName;
	}

	public State(Country country, String stateName, Set<District> districts,
			Set<City> cities) {
		this.country = country;
		this.stateName = stateName;
		this.districts = districts;
		this.cities = cities;
	}

	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
