package com.lbr.dao.hibernate.domain;

// Generated Feb 23, 2011 12:34:52 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Subcategory generated by hbm2java
 */
public class Subcategory implements java.io.Serializable {

	private Integer subCatId;
	private Category category;
	private String subCatName;
	private Boolean type;
	private Set<Events> eventses = new HashSet<Events>(0);

	public Subcategory() {
	}

	public Subcategory(Category category, String subCatName, Boolean type,
			Set<Events> eventses) {
		this.category = category;
		this.subCatName = subCatName;
		this.type = type;
		this.eventses = eventses;
	}

	public Integer getSubCatId() {
		return this.subCatId;
	}

	public void setSubCatId(Integer subCatId) {
		this.subCatId = subCatId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getSubCatName() {
		return this.subCatName;
	}

	public void setSubCatName(String subCatName) {
		this.subCatName = subCatName;
	}

	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	public Set<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(Set<Events> eventses) {
		this.eventses = eventses;
	}

}
