package com.lbr.dao.hibernate.domain;

// Generated Feb 18, 2011 12:19:19 PM by Hibernate Tools 3.4.0.Beta1

/**
 * UserpermissionsId generated by hbm2java
 */
public class UserpermissionsId implements java.io.Serializable {

	private String userTypeName;
	private int userTypeId;
	private Boolean basicModulePermission;
	private Boolean eventsModulePermission;
	private Boolean locationModulePermission;
	private Boolean categoryModulePermission;
	private Boolean purgeModulePermission;
	private String dbUser;

	public UserpermissionsId() {
	}

	public UserpermissionsId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	public UserpermissionsId(String userTypeName, int userTypeId,
			Boolean basicModulePermission, Boolean eventsModulePermission,
			Boolean locationModulePermission, Boolean categoryModulePermission,
			Boolean purgeModulePermission, String dbUser) {
		this.userTypeName = userTypeName;
		this.userTypeId = userTypeId;
		this.basicModulePermission = basicModulePermission;
		this.eventsModulePermission = eventsModulePermission;
		this.locationModulePermission = locationModulePermission;
		this.categoryModulePermission = categoryModulePermission;
		this.purgeModulePermission = purgeModulePermission;
		this.dbUser = dbUser;
	}

	public String getUserTypeName() {
		return this.userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	public int getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	public Boolean getBasicModulePermission() {
		return this.basicModulePermission;
	}

	public void setBasicModulePermission(Boolean basicModulePermission) {
		this.basicModulePermission = basicModulePermission;
	}

	public Boolean getEventsModulePermission() {
		return this.eventsModulePermission;
	}

	public void setEventsModulePermission(Boolean eventsModulePermission) {
		this.eventsModulePermission = eventsModulePermission;
	}

	public Boolean getLocationModulePermission() {
		return this.locationModulePermission;
	}

	public void setLocationModulePermission(Boolean locationModulePermission) {
		this.locationModulePermission = locationModulePermission;
	}

	public Boolean getCategoryModulePermission() {
		return this.categoryModulePermission;
	}

	public void setCategoryModulePermission(Boolean categoryModulePermission) {
		this.categoryModulePermission = categoryModulePermission;
	}

	public Boolean getPurgeModulePermission() {
		return this.purgeModulePermission;
	}

	public void setPurgeModulePermission(Boolean purgeModulePermission) {
		this.purgeModulePermission = purgeModulePermission;
	}

	public String getDbUser() {
		return this.dbUser;
	}

	public void setDbUser(String dbUser) {
		this.dbUser = dbUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserpermissionsId))
			return false;
		UserpermissionsId castOther = (UserpermissionsId) other;

		return ((this.getUserTypeName() == castOther.getUserTypeName()) || (this
				.getUserTypeName() != null
				&& castOther.getUserTypeName() != null && this
				.getUserTypeName().equals(castOther.getUserTypeName())))
				&& (this.getUserTypeId() == castOther.getUserTypeId())
				&& ((this.getBasicModulePermission() == castOther
						.getBasicModulePermission()) || (this
						.getBasicModulePermission() != null
						&& castOther.getBasicModulePermission() != null && this
						.getBasicModulePermission().equals(
								castOther.getBasicModulePermission())))
				&& ((this.getEventsModulePermission() == castOther
						.getEventsModulePermission()) || (this
						.getEventsModulePermission() != null
						&& castOther.getEventsModulePermission() != null && this
						.getEventsModulePermission().equals(
								castOther.getEventsModulePermission())))
				&& ((this.getLocationModulePermission() == castOther
						.getLocationModulePermission()) || (this
						.getLocationModulePermission() != null
						&& castOther.getLocationModulePermission() != null && this
						.getLocationModulePermission().equals(
								castOther.getLocationModulePermission())))
				&& ((this.getCategoryModulePermission() == castOther
						.getCategoryModulePermission()) || (this
						.getCategoryModulePermission() != null
						&& castOther.getCategoryModulePermission() != null && this
						.getCategoryModulePermission().equals(
								castOther.getCategoryModulePermission())))
				&& ((this.getPurgeModulePermission() == castOther
						.getPurgeModulePermission()) || (this
						.getPurgeModulePermission() != null
						&& castOther.getPurgeModulePermission() != null && this
						.getPurgeModulePermission().equals(
								castOther.getPurgeModulePermission())))
				&& ((this.getDbUser() == castOther.getDbUser()) || (this
						.getDbUser() != null && castOther.getDbUser() != null && this
						.getDbUser().equals(castOther.getDbUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUserTypeName() == null ? 0 : this.getUserTypeName()
						.hashCode());
		result = 37 * result + this.getUserTypeId();
		result = 37
				* result
				+ (getBasicModulePermission() == null ? 0 : this
						.getBasicModulePermission().hashCode());
		result = 37
				* result
				+ (getEventsModulePermission() == null ? 0 : this
						.getEventsModulePermission().hashCode());
		result = 37
				* result
				+ (getLocationModulePermission() == null ? 0 : this
						.getLocationModulePermission().hashCode());
		result = 37
				* result
				+ (getCategoryModulePermission() == null ? 0 : this
						.getCategoryModulePermission().hashCode());
		result = 37
				* result
				+ (getPurgeModulePermission() == null ? 0 : this
						.getPurgeModulePermission().hashCode());
		result = 37 * result
				+ (getDbUser() == null ? 0 : this.getDbUser().hashCode());
		return result;
	}

}
