package com.lbr.dao.hibernate;

import com.lbr.dao.hibernate.domain.Locations;

// Generated Feb 19, 2011 11:54:04 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userName;
	private Locations locationsByCurrentLocationId;
	private Locations locationsByHomeLocationId;
	private long mobileNo;
	private String preferences;
	private String password;
	private Integer vicinityPolicyPreference;
	private String email;
	private String address;
	private String preferencesLevels;
	private Integer userTypeId;

	public Users() {
	}

	public Users(String userName, long mobileNo, String password) {
		this.userName = userName;
		this.mobileNo = mobileNo;
		this.password = password;
	}

	public Users(String userName, Locations locationsByCurrentLocationId,
			Locations locationsByHomeLocationId, long mobileNo,
			String preferences, String password,
			Integer vicinityPolicyPreference, String email, String address,
			String preferencesLevels, Integer userTypeId) {
		this.userName = userName;
		this.locationsByCurrentLocationId = locationsByCurrentLocationId;
		this.locationsByHomeLocationId = locationsByHomeLocationId;
		this.mobileNo = mobileNo;
		this.preferences = preferences;
		this.password = password;
		this.vicinityPolicyPreference = vicinityPolicyPreference;
		this.email = email;
		this.address = address;
		this.preferencesLevels = preferencesLevels;
		this.userTypeId = userTypeId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Locations getLocationsByCurrentLocationId() {
		return this.locationsByCurrentLocationId;
	}

	public void setLocationsByCurrentLocationId(
			Locations locationsByCurrentLocationId) {
		this.locationsByCurrentLocationId = locationsByCurrentLocationId;
	}

	public Locations getLocationsByHomeLocationId() {
		return this.locationsByHomeLocationId;
	}

	public void setLocationsByHomeLocationId(Locations locationsByHomeLocationId) {
		this.locationsByHomeLocationId = locationsByHomeLocationId;
	}

	public long getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(long mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getPreferences() {
		return this.preferences;
	}

	public void setPreferences(String preferences) {
		this.preferences = preferences;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getVicinityPolicyPreference() {
		return this.vicinityPolicyPreference;
	}

	public void setVicinityPolicyPreference(Integer vicinityPolicyPreference) {
		this.vicinityPolicyPreference = vicinityPolicyPreference;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPreferencesLevels() {
		return this.preferencesLevels;
	}

	public void setPreferencesLevels(String preferencesLevels) {
		this.preferencesLevels = preferencesLevels;
	}

	public Integer getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

}
